import React, { useState } from 'react'
import { isValidUrl, required } from '../lib/validators'

export default function ArtifactForm({ onSubmit }) {
  const [type, setType] = useState('model')
  const [url, setUrl] = useState('')
  const [error, setError] = useState(null)

  function handleSubmit(e) {
    e.preventDefault()
    setError(null)
    if (!required(url) || !isValidUrl(url)) return setError('Valid URL is required')
    onSubmit({ type, url })
  }

  return (
    <form onSubmit={handleSubmit} className="bg-white p-4 rounded shadow flex flex-col gap-3" aria-label="Create artifact">
      {error && <div className="text-sm text-red-700">{error}</div>}
      <div>
        <label htmlFor="artifactTypeSelect" className="block text-sm font-medium text-gray-700">Artifact Type</label>
        <select id="artifactTypeSelect" value={type} onChange={e => setType(e.target.value)} className="mt-1 p-2 border rounded">
          <option value="model">Model</option>
          <option value="dataset">Dataset</option>
          <option value="code">Code</option>
        </select>
      </div>

      {/* ID is generated by the server; omit in UI */}

      <div>
        <label htmlFor="artifactUrlInput" className="block text-sm font-medium text-gray-700">Artifact URL</label>
        <input id="artifactUrlInput" value={url} onChange={e => setUrl(e.target.value)} className="mt-1 p-2 border rounded w-full" placeholder="https://..." />
      </div>

      <div className="flex gap-2">
        <button className="px-3 py-2 bg-blue-700 text-white rounded" type="submit">Create</button>
      </div>
    </form>
  )
}
